### ISSUE TITLE
Mod crashes with latest version of Vinery (1.4.32)

### ISSUE THREAD

**Issue by subwayatrain** [joe-vettek/Dynamic-Trees-for-Vinery#3]
Vinery has updated to 1.4.32 and forge now throws an error against this mod on loadup. This is using ATM9 with additional mods including DT and applicable addons.

https://pastebin.com/KtExFL7b

**Comment by joe-vettek** [comment]
should be fixed in latest version

**Comment by subwayatrain** [comment]
Thanks for the fast response and update! Tested new update, and it looks like it fixed the issue.
